name = "HydroModelLibrary"
uuid = "f34bc7f3-9d04-4ef8-b7a3-feb87ce2ba93"
authors = ["jingx <50790703+chooron@users.noreply.github.com>"]
version = "0.2.0"

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
HydroModelCore = "57609f06-44cb-4626-8f6d-47ea844d0af1"
HydroModels = "7e3cde01-c141-467b-bff6-5350a0af19fc"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
ComponentArrays = "0.15"
HydroModelCore = "0.2"
HydroModels = "0.4"
SpecialFunctions = "2"
